In [30]:
import pandas as pd
messages=pd.read_csv('./spam.csv',sep=',',names=['label','message'],skiprows=1)
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [31]:
messages['length'] = messages['message'].apply(len)
messages.head()

  label                                            message  length
0   ham  Go until jurong point, crazy.. Available only ...     111
1   ham                      Ok lar... Joking wif u oni...      29
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
3   ham  U dun say so early hor... U c already then say...      49
4   ham  Nah I don't think he goes to usf, he lives aro...      61

In [32]:
from nltk.corpus import stopwords
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [33]:
#NLP - Stopwords removing - Text pre-processing 
import string 
from nltk.corpus import stopwords
stopwords.words('english') 
def text_process(mess):
    nopunc = [char for char in mess if char not in string.punctuation] 
    nopunc = ''.join(nopunc) 
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [34]:
messages['message'].head().apply(text_process)

0    [Go, jurong, point, crazy, Available, bugis, n...
1                       [Ok, lar, Joking, wif, u, oni]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3        [U, dun, say, early, hor, U, c, already, say]
4    [Nah, dont, think, goes, usf, lives, around, t...
Name: message, dtype: object

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
bow_transformer = CountVectorizer(analyzer=text_process).fit(messages['message'])

In [36]:
print(len(bow_transformer.vocabulary_))

11422

In [37]:
#tf idf
messages_bow = bow_transformer.transform(messages['message'])
# print("shape os sparse matrix", messages_bow.shape)
# print("amount of non xero occurence ",messages_bow.mz)
# print("sparsity value : %.2f%%", (100.0 "messages_bow.mz / (messages_bow.shape[0])"))

In [38]:

from sklearn.feature_extraction.text import TfidfTransformer
Tfidf_Transformer = TfidfTransformer().fit(messages_bow)
# tfidf4 = Tfidf_Transformer.transform(bow4)
# print(tfidf4.toarray())

In [39]:
messages_tfidf = Tfidf_Transformer.transform(messages_bow) 
print(messages_tfidf.shape)
from sklearn.naive_bayes import MultinomialNB  
spam_detect_model = MultinomialNB() # model creation 
spam_detect_model.fit(messages_tfidf, messages['label']) # training 
from sklearn.metrics import classification_report  # model evl. 
all_predictions =  spam_detect_model.predict(messages_tfidf) 
print(classification_report(messages['label'], all_predictions))
print(all_predictions) # model testing

(5572, 11422)
              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      4825
        spam       1.00      0.85      0.92       747

    accuracy                           0.98      5572
   macro avg       0.99      0.92      0.95      5572
weighted avg       0.98      0.98      0.98      5572

['ham' 'ham' 'spam' ... 'ham' 'ham' 'ham']

In [41]:
ms4 = messages['message'][3]
bow4 = bow_transformer.transform([ms4])
tfidf4 = Tfidf_Transformer.transform(bow4)
print(tfidf4.toarray())
print(bow4)
print(bow4.shape)
print("Predicted:", spam_detect_model.predict(tfidf4)[0])
print('excepted:', messages.label[3])

[[0. 0. 0. ... 0. 0. 0.]]
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 7 stored elements and shape (1, 11422)>
  Coords	Values
  (0, 4066)	2
  (0, 4627)	1
  (0, 5258)	1
  (0, 6201)	1
  (0, 6219)	1
  (0, 7183)	1
  (0, 9551)	2
(1, 11422)
Predicted: ham
excepted: ham

In [ ]:
# import tensorflow as tf
# from tensorflow.keras.datasets import imdb
# from tensorflow.keras.models import seque

In [42]:
import tensorflow as tf 
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential 
from  tensorflow.keras.layers import Dense 
from tensorflow.keras.layers import SimpleRNN 
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing import sequence 
# fix randon seed for reproduciylity 
tf.random.set_seed(7)

In [43]:
top_words = 500
(x_train,y_train),(x_test,y_test)=imdb.load_data(num_words=top_words)

In [44]:
top_words = 500
(x_train,y_train),(x_test,y_test)=imdb.load_data(num_words=top_words)

In [45]:
max_review_length = 50
x_train = sequence.pad_sequences(x_train,maxlen=max_review_length)
x_test= sequence.pad_sequences(x_test,maxlen=max_review_length)

In [48]:
Embedding_vector_length=32
model = Sequential()
model.add(Embedding(top_words ,Embedding_vector_length,input_shape=(max_review_length,)))
model.add(SimpleRNN(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 50, 32)         │        16,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 100)            │        13,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 29,401 (114.85 KB)

 Trainable params: 29,401 (114.85 KB)

 Non-trainable params: 0 (0.00 B)

None

In [50]:
embedding_vector_length = 32
model = Sequential()
model.add (Embedding(top_words, embedding_vector_length, input_shape=(max_review_length,)))
model.add (SimpleRNN(100))
model.add (Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print (model.summary())
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=3, batch_size=64)
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=3, batch_size=64)

Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 50, 32)         │        16,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (None, 100)            │        13,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 29,401 (114.85 KB)

 Trainable params: 29,401 (114.85 KB)

 Non-trainable params: 0 (0.00 B)

None
Epoch 1/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.5481 - loss: 0.6838 - val_accuracy: 0.6105 - val_loss: 0.6482
Epoch 2/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 9s 22ms/step - accuracy: 0.7144 - loss: 0.5550 - val_accuracy: 0.7500 - val_loss: 0.5139
Epoch 3/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 7s 18ms/step - accuracy: 0.7518 - loss: 0.5083 - val_accuracy: 0.7434 - val_loss: 0.5212
Epoch 1/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.7649 - loss: 0.4926 - val_accuracy: 0.7492 - val_loss: 0.5274
Epoch 2/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - accuracy: 0.7724 - loss: 0.4766 - val_accuracy: 0.7468 - val_loss: 0.5246
Epoch 3/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 13s 33ms/step - accuracy: 0.7812 - loss: 0.4670 - val_accuracy: 0.7483 - val_loss: 0.5333

ModuleNotFoundError: No module named 'dotenv'